version: "3.8"
services:
  rust-dev-service:
    container_name: rust-dev-container
    image: rust-dev-image
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RUST_VERSION=1.73.0-bookworm
        - UID=1000
        - GID=1000
        - USER=rustdev
        - PASSWORD=rustdev
        - SHELL=/bin/bash
    volumes:
      - .:/app
    
